Station1
Tetsuhisa00/go-stations pull request #13
Opened 2023-12-10 11:11 UTC by Tetsuhisa00

station1が完了しました

2023-12-10 11:16 UTC, TakumaKurosawa requested changes

2023-12-10 11:16 UTC, TakumaKurosawa commented on handler/middleware/recovery.go
> +// TODO: ここに実装をする
これ実装したと思うので、消しちゃいましょう！

2023-12-10 11:16 UTC, TakumaKurosawa commented on handler/middleware/recovery.go
> +	}()
formatがおかしそう

2023-12-10 11:16 UTC, TakumaKurosawa commented on handler/panic.go
> +	}
このURLパス判定はRouterでやっているはずなので、不要ですね！

2023-12-11 07:49 UTC, Tetsuhisa00 commented on handler/middleware/recovery.go
> +// TODO: ここに実装をする
修正しました！

2023-12-11 07:49 UTC, Tetsuhisa00 commented on handler/middleware/recovery.go
> +	}()
修正しました！

2023-12-11 07:49 UTC, Tetsuhisa00 commented on handler/panic.go
> +	}
修正しました！

2023-12-13 13:05 UTC, TakumaKurosawa approved these changes
LGTM

2023-12-13 13:05 UTC, merged