Station2
Tetsuhisa00/go-stations pull request #14
Opened 2023-12-13 08:31 UTC by Tetsuhisa00

station2の実装が完了したので確認お願いします！

2023-12-13 13:16 UTC, TakumaKurosawa requested changes

2023-12-13 13:16 UTC, TakumaKurosawa commented on handler/middleware/parse_user_os.go
> +		ctx := context.WithValue(r.Context(), UserOSKey("UserOS"), ua.OS)
`UserOSKey` のカスタム型を作るのはOKなので、定数でKeyを宣言しちゃいましょう！

2023-12-13 13:22 UTC, TakumaKurosawa approved these changes
LGTM

2023-12-13 13:40 UTC, Tetsuhisa00 commented on handler/middleware/parse_user_os.go
> +		ctx := context.WithValue(r.Context(), UserOSKey("UserOS"), ua.OS)
修正しました。以下修正後のコードです。
```go
package middleware

import (
	"context"
	"net/http"
	"github.com/mileusna/useragent"
)

type userOSKey string 
const uoskey = userOSKey("UserOS")   //修正部分

func ParseUserOS(h http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		ua := useragent.Parse(r.UserAgent())
		ctx := context.WithValue(r.Context(), uoskey, ua.OS)
		h.ServeHTTP(w, r.WithContext(ctx))
	}
	return http.HandlerFunc(fn)
}
```

2023-12-14 13:21 UTC, TakumaKurosawa approved these changes

2023-12-14 13:21 UTC, merged